### ISSUE TITLE
Possible to add support for types?

### ISSUE THREAD

**Issue by tylerlaprade** [skorokithakis/django-annoying#103]
I have been enjoying using `get_object_or_None` all over my project in place of lazy incorrect `.first()` calls, and it's really great. However, it has the downside of losing the information about the object's type. Pyright tells me the returned type is `Unknown | None`, even though I know it has to be the corresponding type of the `Model | QuerySet | BaseManager` that I passed as `klass`.

<img width="336" alt="image" src="https://github.com/skorokithakis/django-annoying/assets/5475199/0bc5e2a8-567c-4618-8960-9b6f4a405293">

**Comment by skorokithakis** [comment]
Types are definitely something that need to be added, any contributing PRs are welcome!

**Comment by tylerlaprade** [comment]
Thanks @skorokithakis! When do you think it will be released?

**Comment by skorokithakis** [comment]
Released [0.10.7](https://pypi.org/manage/project/django-annoying/release/0.10.7/), sorry for the delay!

**Comment by tylerlaprade** [comment]
No worries, thank you so much!
