### ISSUE TITLE
New PyPi Release?

### ISSUE THREAD

**Issue by krallin** [skorokithakis/django-annoying#34]
Hey there,

The last release of `django-annoying` to PyPi was 9 months ago, and several changes have been made since (e.g. making `JSONField` compatible with Python 3). 

Is a new release planned for soon?

Thanks!

**Comment by skorokithakis** [comment]
Hello! I can definitely make a release now, thanks for the heads up.

**Comment by skorokithakis** [comment]
Done, thanks! https://pypi.python.org/pypi/django-annoying

**Comment by krallin** [comment]
Nice, thanks!

Cheers,
