### ISSUE TITLE
An AutoOneToOneField that works with Django 1.8

### ISSUE THREAD

**Issue by beaugunderson** [skorokithakis/django-annoying#36]
If anyone comes here looking for it here's the relevant bit:

```python
class AutoSingleRelatedObjectDescriptor(SingleRelatedObjectDescriptor):
    """
    The descriptor that handles the object creation for an AutoOneToOneField.
    """
    def __get__(self, instance, instance_type=None):
        model = getattr(self.related, 'related_model', self.related.model)

        try:
            return (super(AutoSingleRelatedObjectDescriptor, self)
                    .__get__(instance, instance_type))
        except model.DoesNotExist:
            obj = model(**{self.related.field.name: instance})

            obj.save()

            # Don't return obj directly, otherwise it won't be added
            # to Django's cache, and the first 2 calls to obj.relobj
            # will return 2 different in-memory objects
            return (super(AutoSingleRelatedObjectDescriptor, self)
                    .__get__(instance, instance_type))
```

**Comment by skorokithakis** [comment]
Thanks for this. Can you open a PR? Is it backwards-compatible?

**Comment by beaugunderson** [comment]
@nutztherookie I don't think my technique is backwards-compatible though is the only issue :)

**Comment by skorokithakis** [comment]
Thanks for the PR! If I understood correctly, this is to avoid the `ValueError`, right? In that case, the change is backwards-incompatible indeed, but does it work at all without this?

I haven't used 1.8 yet, and I rarely use this field, but if it breaks completely with 1.8, we should probably do it this way. Maybe adding a check for the Django version would be prudent.

**Comment by nutztherookie** [comment]
It does work partially - I think pulling the object worked, but not auto-creating it. I will try and create a version-agnostic patch asap

**Comment by nutztherookie** [comment]
actually.. I just tested a bit and I'm pretty sure it IS backward-compatible. tried django 1.7 and django 1.6 and both work fine with the new code.

**Comment by skorokithakis** [comment]
Alright, it looks backwards-compatible to me too, and this is the way Django recommends, so I'll merge it, thank you!

**Comment by nutztherookie** [comment]
@skorokithakis would it be okay for you to release django-annoying with this fixed?
It'd be better here at work to be able to pull from pypi (via pip)

Thanks a lot

**Comment by skorokithakis** [comment]
Sure, no problem. I will do it shortly, thanks!

**Comment by skorokithakis** [comment]
The dev->master diff tells me I made too many changes in my botched py3k attempt, so I'll have to fix those before I can release it...

**Comment by Kobold** [comment]
Thanks for all the work! Just wanted to leave the feedback that `AutoOneToOneField` is the primary reason I use django-annoying.

**Comment by nutztherookie** [comment]
thanks as well! and: same here ;)
