### ISSUE TITLE
Test don't run against Django 1.7+

### ISSUE THREAD

**Issue by Geekfish** [skorokithakis/django-annoying#40]
As the title says, when trying to run the tests against Django 1.7.5 or Django 1.8.5 I get the following traceback:
```python
Traceback (most recent call last):
  File "test.py", line 35, in <module>
    models.loading.cache.app_store[type(this + '.models', (), {'__file__':__file__})] = this
AttributeError: 'module' object has no attribute 'loading'
```
I'm not sure what the "official" supported versions of Django for this library are.

**Comment by skorokithakis** [comment]
Hmm, yes. This is because it's deprecated:

http://stackoverflow.com/a/26126935

I'll try to find some time to fix it, but if anyone else can get to it first, please be my guest and open a PR.

**Comment by skorokithakis** [comment]
This should be fixed now, thanks!
