### ISSUE TITLE
Django 1.9

### ISSUE THREAD

**Issue by debnet** [skorokithakis/django-annoying#44]
```
InvalidTemplateLibrary at /admin/login/
Invalid template library specified. ImportError raised when trying to load 'annoying.templatetags.annoying': No module named 'smart_if'
```

Thanks.

**Comment by ckcnik** [comment]
Hi, I have the same error. I think there is not enough points - http://joxi.ru/MAjMzx9tv4oa42 
I did the fork - https://github.com/ckcnik/django-annoying

**Comment by skorokithakis** [comment]
Fixed!

**Comment by ckcnik** [comment]
Thanks!

**Comment by vladir** [comment]
Hi all, so is Django 1.9 supported now? Thanks :)

**Comment by skorokithakis** [comment]
It should be! Please open a PR (or at least an issue) if you run into any problems!

**Comment by vladir** [comment]
Thanks a lot for your quick reply @skorokithakis . I'm on the process of upgrading a project to Django 1.9, and I'm using django-annoying :). For sure if I find any issue I will follow your suggestion :). Thanks again!
