### ISSUE TITLE
Remove pretty-print from the JSON field output or make it configurable

### ISSUE THREAD

**Issue by kabakchey** [skorokithakis/django-annoying#53]
Pretty-print adds huge space overhead to the output. This feature doesn't give any options in case when we want to inherit the class for encryption except using v0.8.7 which is the latest one without pretty-print.

**Comment by skorokithakis** [comment]
That's a good idea, ideally you could pass a function to the field to be called on the JSON string before saving. Something like `JSONField(transform_func=pprint.pprint)`. Would you be interested in issuing a PR?

**Comment by skorokithakis** [comment]
Thank you!
