### ISSUE TITLE
Please add a release with a universal wheel to PyPI

### ISSUE THREAD

**Issue by jdufresne** [skorokithakis/django-annoying#81]
Universal wheel support was added in commit a8dd7ebaacf8343c84f2a1a49f8b1c17ce53e031#diff-380c6a8ebbbce17d55d50ef17d3cf906.

If you look on PyPI, there is not a universal wheel, only a Pythoh2-only one.

https://pypi.python.org/pypi/django-annoying

Can you please upload a universal wheel? Either as a new release or for the existing release? Thanks.

More information here:

https://pythonwheels.com/

**Comment by skorokithakis** [comment]
Huh, that's odd, the `setup.cfg` does specify `universal = 1`, and `bdist_wheel` should have created it. Regardless, I have uploaded the new wheel, let me know if there's something wrong with it, and thanks for the report!
