### ISSUE TITLE
Could you publish a new release?

### ISSUE THREAD

**Issue by bogdanpetrea** [skorokithakis/django-annoying#85]
Hi @skorokithakis,
First of all, thanks for such an awesome project!

I'm particularly in need of this fix https://github.com/skorokithakis/django-annoying/commit/563c157f8c113bbb3f48813419f87caf169ba455 and I wouldn't want to pin a GitHub commit as a requirement.

**Comment by skorokithakis** [comment]
Hello! Certainly, have you tried master and is it working for you? My apprehension is that it might break older Django installations...

**Comment by skorokithakis** [comment]
I have released 0.10.5, please let me know if it works!

**Comment by bogdanpetrea** [comment]
Thanks for being so quick!

All I had to do was rename `annoying.fields.JSONField.dumps` to `annoying.fields.dumps` in older migrations. Other than that, `./manage.py makemigrations` worked fine with the new 0.10.4 version.

I'll let you know if something doesn't work right, after I run some tests.

**Comment by skorokithakis** [comment]
Ah, damn, that's unfortunate. Now a bunch of people's stuff is going to break. I'll need to create a dummy `dumps` in `JSONField`...
