### ISSUE TITLE
Setting HTTP status code when using ajax_request

### ISSUE THREAD

**Issue by Flimm** [skorokithakis/django-annoying#93]
The `ajax_request` decorator lets you return a dictionary or list from your function, and it will convert it to JSON for you.

I would like to return a dictionary representing an error, and I would like to set the HTTP code to something other than 200, maybe 400 Bad Request. How can I do that if I am using `ajax_request`?

```python3
from annoying.decorators import ajax_request

@ajax_request
def foobar(request):
    # how do I set HTTP status code to 400?
    return {"error": "example"}
```

**Comment by skorokithakis** [comment]
I generally return an `HttpResponse` in those cases, since there isn't really a good way to do this otherwise...

**Comment by skorokithakis** [comment]
You don't need to take the decorator out, it will just an `HttpResponse` through.

**Comment by Flimm** [comment]
So I would have to do:

```python
from annoying.decorators import ajax_request
from django.http import HttpResponse
import json

@ajax_request
def foobar(request):
    return HttpResponse(
        json.dumps({"error": "example"}),
        status=400,
        content_type="application/json"
    )
```

or the shorter:

```python
from django.http import JsonResponse

def foobar(request):
    return JsonResponse({"error": "example"}, status=400)
```

Thanks for the answer, @skorokithakis . I think for my purposes, I'll just use [`JsonResponse`](https://docs.djangoproject.com/en/stable/ref/request-response/#jsonresponse-objects) instead of `ajax_request`.
