### ISSUE TITLE
I know this is ancient history but a breaking change in a point release?

### ISSUE THREAD

**Issue by andybak** [skorokithakis/django-annoying#96]
https://github.com/skorokithakis/django-annoying/blob/0eb5297d56770477da16dabb0cb68a9909386e77/annoying/fields.py#L7

Just updating a legacy project and this threw me for a while.

**Comment by skorokithakis** [comment]
It's a breaking change? What did it break?

**Comment by andybak** [comment]
Breaks on Django 1.8.x (I told you it was ancient history!)

And yes - we're still supporting 1.8.x - working through a long client list gradually getting everyone on 2.x but it's an uphill struggle.

I had django-annoying>=0.10.3,<0.11 in requirements and it broke on a clean local install. Django 1.10 dropped the old method names but I would have expected annoying to support them until 1.9.x

**Comment by skorokithakis** [comment]
Hm, yes, this is an oversight. Can you issue a PR that works on both? I don't have a 1.8 installation handy.

**Comment by andybak** [comment]
Sure thing

**Comment by panosangelopoulos** [comment]
@skorokithakis what about closing the issue?

**Comment by skorokithakis** [comment]
Good call, thanks @panosangelopoulos.
