### ISSUE TITLE
Support for django v3

### ISSUE THREAD

**Issue by bakonyidani** [skorokithakis/django-annoying#99]
I am currently trying to update to using django 3.0.3, but django-annoying throws an error:

```
 File "/home/dani/anaconda3/envs/artheseus/lib/python3.7/site-packages/annoying/fields.py", line 11, in <module>
    from django.utils import six
ImportError: cannot import name 'six' from 'django.utils' (/home/dani/anaconda3/envs/artheseus/lib/python3.7/site-packages/django/utils/__init__.py)
```

Indedd django.utils.six. was removed in version 3:
https://github.com/django/django/commit/41384812efe209c8295a50d78b45e0ffb2992436

**Comment by skorokithakis** [comment]
Hmm, yes, that's true. Would you mind issuing a PR with a conditional import that works on 3?

**Comment by ZeroCoolHacker** [comment]
I believe its done so the issue should be closed now

**Comment by skorokithakis** [comment]
Good call, thanks!
